# Generated by Django 3.2.5 on 2021-07-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fitomassa', models.FloatField()),
                ('kgco2', models.FloatField()),
                ('meses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Foresta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kgco2', models.FloatField()),
            ],
        ),
    ]
