# Generated by Django 3.2.5 on 2021-07-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='plha',
            field=models.IntegerField(default=0),
        ),
    ]
